### ISSUE TITLE
BUG: Problem using covSpectrum mutation share - Ns are treated as reference

### ISSUE THREAD

**Issue by corneliusroemer** [lenaschimmel/sc2rf#23]
There's a bit of a problem with using covSpectrum's current mutation API implementation: Ns in any sample is treated as reference.

This can cause confusion. For example, I thought that this intermission here within Spike was a bad sign:
![image](https://user-images.githubusercontent.com/25161793/161263608-145dbc67-2b78-4666-b24b-968cb7e01c2b.png)
https://github.com/cov-lineages/pango-designation/issues/498

But it isn't! Both 22813 and 22882 are defining for both BA.1 and BA.2. However, both are apparently `N` in 40% of sequences in BA.1. Causing sc2rf to think that it's in fact not a defining mutation in BA.1 making spurious intermissions appear.

I'm not sure how to work around this best. Really, this should be fixed in covSpectrum: `N`s should be left out of mutation proportion calculations - and not be treated as reference (implicitly).

@chaoran-chen can you think of a workaround? How can one get the share of Ns for a query? Could that maybe be supplied by a new API endpoint?

Usually, `N`s don't make up 40% of a site, but sometimes they do and that can cause problems like here, where one falsely thinks there's a non-clean breakpoint.

**Comment by lenaschimmel** [comment]
Great observation! Yeah, now that I read it here, it reminded me of a [tweeted cov-spectrum screenshot](https://twitter.com/covSpectrum/status/1509167474742370311) I saw recently. There it says _"Please note that we currently do not exclude the unknowns when calculating the proportions."_ - so there's already awareness of that.

I just noticed that you can actually query for Ns, I guess I need to slightly modify the query to get a share instead of / in addition to the absolute count: https://lapis.cov-spectrum.org/open/v1/sample/aggregated?nucMutations=22813N&fields=pangoLineage

**Comment by corneliusroemer** [comment]
Ah great, yes you can use this as a workaround if you query like that. Smart @lenaschimmel, didn't think of that.

**Comment by lenaschimmel** [comment]
And now I just saw that the cov-spectrum webiste can filter for various quality metrics since [this PR](https://github.com/cevo-public/cov-spectrum-website/pull/450#issue-1189621091) was merged.

![screenshot](https://user-images.githubusercontent.com/18666552/161250342-12a2c8ec-6828-489c-9029-bd926bc0947b.png)

Just wondering if this is possible via the API too, and if it would also solve the problem. 

(I will have a look later, since it probably is well documented, just need to write this down now.)

**Comment by corneliusroemer** [comment]
Hmm, not sure it'll help much with the N problem but worth a try.

**Comment by chaoran-chen** [comment]
The QC values are not yet available for the public instance of the API (but hopefully by the end of next week).

**Comment by lenaschimmel** [comment]
I've started working on this, but it's not trivial. I need to make a request for each coordinate which has a relevant mutation in at least one lineage/clade. There are (currently) 888 of those locations. Making the 888 requests will take about 4 minutes (extrapolated from the first 79 I tried) so that's an upper bound on how much load it puts on the API server.

(Is there a way I can do it in much less than 888 requests? I currently don't see a way to aggregate it, and no way to filter out coordinate for which the result would not be relevant anyway.)

Mapping the per-coordinate results to the per-lineage results to recompute the prevalences is then just a lot of data wrangling in a few nested loops, but I'm too tired to finish it today.

**Comment by corneliusroemer** [comment]
I don't think this overloads the server, LAPIS is pretty good :)

You could also make requests in parallel to speed things up if you don't want to wait for 4 minutes.

**Comment by lenaschimmel** [comment]
That's great!

I never got around to finish my workaround, but now I could just re-run `./sc2rf.py --rebuild-examples` and commit the new [virus_properties.json](https://github.com/lenaschimmel/sc2rf/blob/5ac8d04550d2cd253ccb80894371ca2d327365e9/virus_properties.json). 

Both 22813 and 22882 look ok now and a few other sites have also crossed the default `--mutation-threshold`.

<img width="934" alt="Bildschirmfoto 2022-04-11 um 15 37 58" src="https://user-images.githubusercontent.com/1325019/162753457-7cf363ae-17bb-49d7-9634-2074f192e497.png">

_(Please excuse my sloppy graphic editing)_
